/**
 * BlueprintPrintView — The main composition component
 * 
 * Assembles all blueprint sub-components into a single printable document.
 * This is the DOM node that gets captured by html2canvas → jsPDF.
 */

import { forwardRef } from "react";
import { getPalette } from "./BlueprintPalette";
import BlueprintSVGPatterns from "./BlueprintSVGPatterns";
import BlueprintTitleCartouche from "./BlueprintTitleCartouche";
import BlueprintNotesPanel from "./BlueprintNotesPanel";
import BlueprintStepPlate from "./BlueprintStepPlate";
import BlueprintRiskAnnotations from "./BlueprintRiskAnnotations";
import BlueprintCriteriaFooter from "./BlueprintCriteriaFooter";

const BlueprintPrintView = forwardRef(function BlueprintPrintView({ run, isDark }, ref) {
  const palette = getPalette(isDark);
  const bp = run?.blueprint;

  if (!bp) {
    return (
      <div ref={ref} style={{ padding: 40, textAlign: "center", color: palette.muted }}>
        No blueprint data available for this run.
      </div>
    );
  }

  return (
    <div
      ref={ref}
      style={{
        width: "100%",
        maxWidth: 900,
        margin: "0 auto",
        background: palette.backgroundGradient,
        position: "relative",
        padding: "40px 48px",
        boxSizing: "border-box",
        fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
        color: palette.text,
        overflow: "hidden",
      }}
    >
      {/* Background: grid + sacred geometry watermark */}
      <BlueprintSVGPatterns palette={palette} />

      {/* Content layer — above the patterns */}
      <div style={{ position: "relative", zIndex: 1 }}>
        {/* ─── BORDER FRAME (architectural drawing border) ─── */}
        <div
          style={{
            position: "absolute",
            inset: -20,
            border: `2px solid ${palette.borderLine}`,
            pointerEvents: "none",
          }}
        />
        <div
          style={{
            position: "absolute",
            inset: -16,
            border: `0.5px solid ${palette.borderLineLight}`,
            pointerEvents: "none",
          }}
        />

        {/* ─── TITLE CARTOUCHE ─── */}
        <BlueprintTitleCartouche run={run} palette={palette} />

        {/* ─── GENERAL NOTES + ALTERNATIVES ─── */}
        <BlueprintNotesPanel blueprint={bp} palette={palette} />

        {/* ─── IMPLEMENTATION STEPS (the plates) ─── */}
        {bp.steps?.length > 0 && (
          <div style={{ marginBottom: 28 }}>
            <div style={{
              fontFamily: "Georgia, serif",
              fontSize: 12,
              fontWeight: 700,
              letterSpacing: "0.12em",
              textTransform: "uppercase",
              color: palette.copper,
              marginBottom: 16,
              paddingBottom: 6,
              borderBottom: `1.5px solid ${palette.borderLine}`,
            }}>
              Implementation Steps — {bp.steps.length} Phase{bp.steps.length !== 1 ? "s" : ""}
            </div>
            {bp.steps.map((step, i) => (
              <BlueprintStepPlate
                key={i}
                step={step}
                totalSteps={bp.steps.length}
                palette={palette}
                blueprintLevel={run.blueprint_level}
              />
            ))}
          </div>
        )}

        {/* ─── RISK REGISTER ─── */}
        <BlueprintRiskAnnotations risks={bp.risk_register} palette={palette} />

        {/* ─── SUCCESS CRITERIA (Verification Schedule) ─── */}
        <BlueprintCriteriaFooter criteria={bp.success_criteria} palette={palette} />

        {/* ─── FOOTER STAMP ─── */}
        <div style={{
          textAlign: "center",
          padding: "16px 0 0",
          borderTop: `1.5px solid ${palette.borderLine}`,
        }}>
          <span style={{
            fontFamily: "Georgia, serif",
            fontSize: 10,
            letterSpacing: "0.15em",
            textTransform: "uppercase",
            color: palette.copperLight,
          }}>
            Generated by Janus Blueprint Protocol — Cephalon Continuity Framework
          </span>
        </div>
      </div>
    </div>
  );
});

export default BlueprintPrintView;